final movies = <dynamic>[
  {
    'Title': 'COMÉDIA COFFEE BREAK II EDIÇÃO',
    'Image':
        'https://i.ibb.co/21z3Pr7s/comedia.webp',
    'Director': 'Beira, Sofala',
    'rating': '5.0',
    'duration': "2h:42m",
    'type': 'Show',
    'year': '2000',
    'genre': 'Comedy',
    'description': 'Kevin and Perry are two teenagers from London who dream of becoming famous DJs. They head to Ibiza for a holiday where they hope to fulfill their dreams of fame, fortune and pulling girls.',
    'cast': ['Harry Enfield', 'Kathy Burke', 'Rhys Ifans'],
    'price': 30.00,
    'venue': 'Comedy Club Cinema',
    'date': '2024-07-18',
    'time': '21:00',
  },
     {
    'Title': 'Joker',
    'Image':
        'https://www.tallengestore.com/cdn/shop/products/Joker_-_Put_On_A_Happy_Face_-_Joaquin_Phoenix_-_Hollywood_English_Movie_Poster_3_de5e4cfc-cfd4-4732-aad1-271d6bdb1587.jpg?v=1579504979',
    'Director': 'Beira, Sofala',
    'rating': '5.0',
    'duration': "2h:42m",
    'type': 'movie',
    'year': '2000',
    'genre': 'Comedy',
    'description': 'Kevin and Perry are two teenagers from London who dream of becoming famous DJs. They head to Ibiza for a holiday where they hope to fulfill their dreams of fame, fortune and pulling girls.',
    'cast': ['Harry Enfield', 'Kathy Burke', 'Rhys Ifans'],
    'price': 30.00,
    'venue': 'Comedy Club Cinema',
    'date': '2024-07-18',
    'time': '21:00',
  },
  {
    'Title': 'Pathan',
    'Image':'https://www.tallengestore.com/cdn/shop/products/Pathan-ShahRukhKhan-BollywoodHindiMoviePoster_d4846edc-20de-497e-ab2c-07a53e52e268.jpg?v=1675251724',
    'Director': ' Beira, Sofala',
    'rating': '5.0',
    'duration': "2h:10m",
    'type': 'movie',
    'year': '2000',
    'genre': 'Comedy',
    'description': 'Kevin and Perry are two teenagers from London who dream of becoming famous DJs. They head to Ibiza for a holiday where they hope to fulfill their dreams of fame, fortune and pulling girls.',
    'cast': ['Harry Enfield', 'Kathy Burke', 'Rhys Ifans'],
    'price': 30.00,
    'venue': 'Comedy Club Cinema',
    'date': '2024-07-18',
    'time': '21:00',
  },
  {
    'Title': 'Big',
    'Image':'https://i.ibb.co/Q3QJdNZn/La-Casa-de-Papel.webp',
    'Director': 'Beira, Sofala',
    'rating': '4.6',
    'duration': "1h:45m",
    'type': 'movie',
    'year': '2000',
    'genre': 'Comedy',
    'description': 'Kevin and Perry are two teenagers from London who dream of becoming famous DJs. They head to Ibiza for a holiday where they hope to fulfill their dreams of fame, fortune and pulling girls.',
    'cast': ['Harry Enfield', 'Kathy Burke', 'Rhys Ifans'],
    'price': 30.00,
    'venue': 'Comedy Club Cinema',
    'date': '2024-07-18',
    'time': '21:00',
  },
    {
    'Title': 'Champions League Final',
    'Image':'https://i.ibb.co/8gPQtyMX/final.webp'
        ,
    'Director': 'Beira, Sofala',
    'rating': '5.0',
    'duration': "2h:42m",
    'type': 'movie',
    'year': '2000',
    'genre': 'Comedy',
    'description': 'Kevin and Perry are two teenagers from London who dream of becoming famous DJs. They head to Ibiza for a holiday where they hope to fulfill their dreams of fame, fortune and pulling girls.',
    'cast': ['Harry Enfield', 'Kathy Burke', 'Rhys Ifans'],
    'price': 30.00,
    'venue': 'Comedy Club Cinema',
    'date': '2024-07-18',
    'time': '21:00',
  },
  {
    'Title': 'KEVIN & PERRY',
    'Image':'https://i.ibb.co/BVff3hcS/vingadores.webp'
        ,
    'Director': 'Beira, Sofala',
    'rating': '4.0',
    'duration': "1h:22m",
    'type': 'movie',
    'year': '2000',
    'genre': 'Comedy',
    'description': 'Kevin and Perry are two teenagers from London who dream of becoming famous DJs. They head to Ibiza for a holiday where they hope to fulfill their dreams of fame, fortune and pulling girls.',
    'cast': ['Harry Enfield', 'Kathy Burke', 'Rhys Ifans'],
    'price': 30.00,
    'venue': 'Comedy Club Cinema',
    'date': '2024-07-18',
    'time': '21:00',
  },
  {
    'Title': 'Beira É WAWA',
    'Image':'https://i.ibb.co/dJJY1BYW/mbuya-lu.jpg'
        ,
    'Director': 'Mbuya Lu',
    'rating': '4.0',
    'duration': "1h:22m",
    'type': 'movie',
    'year': '2000',
    'genre': 'Comedy',
    'description': 'Kevin and Perry are two teenagers from London who dream of becoming famous DJs. They head to Ibiza for a holiday where they hope to fulfill their dreams of fame, fortune and pulling girls.',
    'cast': ['Harry Enfield', 'Kathy Burke', 'Rhys Ifans'],
    'price': 30.00,
    'venue': 'Comedy Club Cinema',
    'date': '2024-07-18',
    'time': '21:00',
  }
];
